# Generated by Django 3.2.5 on 2021-07-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('bio', models.TextField()),
                ('dark_mode', models.BooleanField()),
                ('language', models.CharField(max_length=3)),
            ],
        ),
    ]
